# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

en:
  languageCode: en
  contentDir: content/en
  params:
    marketing:
      seo:
        description: >-
          PhD Student in Language Analysis and Processing at Hitz Center IXA Group UPV/EHU. Working on Improving Language Models for Low-resource Languages. Graduate in Informatics Engineering with speciality in Software Engineering. Master in Language Analysis and Processing.
    locale:
      address_format: en
      date_format: 01-02-2006

es:
  languageCode: es
  contentDir: content/es
  params:
    marketing:
      seo:
        description: >-
          Estudiante de Doctorado en Análisis y Procesamiento del Lenguaje en HiTZ Center IXA Group (UPV/EHU). Trabajando en mejorar los modelos de lenguaje para idiomas con pocos recursos. Graduado en Ingeniería Informática con especialidad en Ingeniería del Software. Máster en Análisis y Procesamiento del Lenguaje.
    locale:
      address_format: es
      date_format: 01-02-2006

eu:
  languageCode: eu
  contentDir: content/eu
  params:
    marketing:
      seo:
        description: >-
          Hizkuntzaren Azterketa eta Prozesamendua Doktoregoko ikaslea HiTZ Zentroko IXA taldean (UPV/EHU). Hizkuntza ereduak baliabidea urriko hizkuntzetako hobetzeko lanean. Informatika Ingeniaritzan graduatua Software Ingeniaritza espezialitatearekin. Hizkuntzaren Azterketa eta Prozesamendua Masterra.
    locale:
      address_format: es
      date_format: '2006-01-02'
