# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

en:
  languageCode: en
  contentDir: content/en
  params:
    marketing:
      seo:
        description: >-
          PhD Student in Language Analysis and Processing at the Faculty of Informatics of the University of the Basque Country (UPV/EHU). Graduate in Informatics Engineering with speciality in Software Engineering. Master in Language Analysis and Processing.
    locale:
      address_format: en
      date_format: 01-02-2006

es:
  languageCode: es
  contentDir: content/es
  params:
    marketing:
      seo:
        description: >-
          Estudiante de Doctorado en Análisis y Procesamiento del Lenguaje en la Facultad de Informática de la Universidad del País Vasco (UPV/EHU). Graduado en Ingeniería Informática con especialidad en Ingeniería del Software. Máster en Análisis y Procesamiento del Lenguaje.
    locale:
      address_format: es
      date_format: 01-02-2006

eu:
  languageCode: eu
  contentDir: content/eu
  params:
    marketing:
      seo:
        description: >-
          Hizkuntzaren Azterketa eta Prozesamendua Doktoregoko ikaslea Euskal Herriko Unibertsitateko (UPV/EHU) Informatika Fakultatean. Informatika Ingeniaritzan graduatua Software Ingeniaritza espezialitatearekin. Hizkuntzaren Azterketa eta Prozesamendua Masterra.
    locale:
      address_format: es
      date_format: '2006-01-02'
